# Welcome to Jekyll!

# Website settings
title: "Data Me What"
description: "Don't be caught with your data down"
keywords: "tjspross,tj spross, spross, data me what,github,gh-pages"
baseurl: ""

url: "datamewhat.com"
# url: "http://127.0.0.1:4000"


# author
author:
  name: 'TJ'
  first_name: 'Spross'
  last_name: 'TJ'
  email: 'tjspross@gmail.com'
  facebook_username: 'jiakunnj'
  github_username: 'tjspross'

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"


# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
